# Introduction to Functions

Functions are an extremely powerful tool for programming. My goal with this chapter is not to get you to write functions but to help you understand their purpose and to recognize them when you use them. For now, we will work with functions that have been written by others until we learn to write functions of our own.

Let's explore why functions are useful and how to go about building them by teaching a computer to make tea. Now, asking your computer to make tea is very different from say asking a friend of yours to make you tea. 

Your friend doesn't need step by step instructions to make tea. In fact tin your friend would probably think that you were crazy if you told them something like "put the kettle on the stove and wait for the water to come to a boil and then open the cupboard to get a cup".

But a computer on the other hand needs every specific and precise step by step instructions to make tea. So let's look at two ways to provide this instruction. One without functions and another using functions.

Let's start by turning on our computer and asking it to boil some water for the tea.

First you need to get the kettle from your cupboard.This would involve going to the cupboard, opening it, and then pulling out the kettle from the cupboard and then closing the cupboard.

Next you will need to fill water in the kettle for a cup of tea. This involves going to the tap and filling enough water for a cup.

Next let's give instruction to boil this water. 


Place kettle on stove.
